# Generated by Django 6.0.2 on 2026-03-02 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=80)),
                ('duracion_minutos', models.PositiveIntegerField(default=30)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HorarioLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('dia_semana', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['dia_semana', 'hora_inicio'],
                'unique_together': {('dia_semana', 'hora_inicio', 'hora_fin')},
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('estado', models.CharField(choices=[('PENDIENTE_PAGO', 'Pendiente de pago'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada'), ('EXPIRADA', 'Expirada')], default='PENDIENTE_PAGO', max_length=20)),
                ('recordatorio_enviado', models.BooleanField(default=False)),
                ('cancelada_en', models.DateTimeField(blank=True, null=True)),
                ('referencia', models.CharField(blank=True, max_length=80)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='clientes.cliente')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='reservas.servicio')),
            ],
            options={
                'ordering': ['-fecha', '-hora_inicio'],
                'indexes': [models.Index(fields=['fecha', 'hora_inicio'], name='reservas_re_fecha_ef1cad_idx'), models.Index(fields=['estado'], name='reservas_re_estado_7c17e1_idx')],
            },
        ),
    ]
