# Generated by Django 6.0.2 on 2026-03-02 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(blank=True, max_length=80)),
                ('telefono', models.CharField(max_length=30, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Conversacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(choices=[('MENU', 'Menú'), ('ESPERANDO_SERVICIO', 'Esperando servicio'), ('ESPERANDO_FECHA', 'Esperando fecha'), ('ESPERANDO_HORA', 'Esperando hora'), ('ESPERANDO_PAGO', 'Esperando pago'), ('CONFIRMADO', 'Confirmado'), ('CANCELADO', 'Cancelado')], default='MENU', max_length=30)),
                ('datos', models.JSONField(blank=True, default=dict)),
                ('ultima_interaccion', models.DateTimeField(auto_now=True)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conversacion', to='clientes.cliente')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
