# Generated by Django 6.0.2 on 2026-03-02 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('mp_preference_id', models.CharField(blank=True, max_length=120)),
                ('mp_payment_id', models.CharField(blank=True, max_length=120)),
                ('mp_status', models.CharField(blank=True, max_length=30)),
                ('init_point', models.URLField(blank=True)),
                ('external_reference', models.CharField(blank=True, max_length=80)),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('moneda', models.CharField(default='ARS', max_length=10)),
                ('estado', models.CharField(choices=[('CREADO', 'Creado'), ('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('CANCELADO', 'Cancelado')], default='CREADO', max_length=20)),
                ('reserva', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pago', to='reservas.reserva')),
            ],
        ),
        migrations.CreateModel(
            name='PagoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('topic', models.CharField(blank=True, max_length=80)),
                ('action', models.CharField(blank=True, max_length=80)),
                ('mp_id', models.CharField(blank=True, max_length=120)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='pagos.pago')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['estado'], name='pagos_pago_estado_c1c831_idx'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['mp_payment_id'], name='pagos_pago_mp_paym_556204_idx'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['mp_preference_id'], name='pagos_pago_mp_pref_8e7473_idx'),
        ),
    ]
